// <auto-generated />
using System;
using Shyrian_project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Shyrian_project.Migrations
{
    [DbContext(typeof(appDbContext))]
    [Migration("20260510175729_final_database_changes")]
    partial class final_database_changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shyrian_project.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@shyrian.com",
                            Password = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92"
                        });
                });

            modelBuilder.Entity("Shyrian_project.Models.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HospitalCityId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalGovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedDonorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("CityId");

                    b.HasIndex("HospitalCityId");

                    b.HasIndex("HospitalGovernorateId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("SelectedDonorId");

                    b.ToTable("BloodRequests");
                });

            modelBuilder.Entity("Shyrian_project.Models.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A+"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A-"
                        },
                        new
                        {
                            Id = 3,
                            Name = "B+"
                        },
                        new
                        {
                            Id = 4,
                            Name = "B-"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AB+"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AB-"
                        },
                        new
                        {
                            Id = 7,
                            Name = "O+"
                        },
                        new
                        {
                            Id = 8,
                            Name = "O-"
                        });
                });

            modelBuilder.Entity("Shyrian_project.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GovernorateId = 1,
                            Name = "أسيوط"
                        },
                        new
                        {
                            Id = 2,
                            GovernorateId = 1,
                            Name = "أسيوط الجديدة"
                        },
                        new
                        {
                            Id = 3,
                            GovernorateId = 1,
                            Name = "الفتح"
                        },
                        new
                        {
                            Id = 4,
                            GovernorateId = 2,
                            Name = "مدينة نصر"
                        },
                        new
                        {
                            Id = 5,
                            GovernorateId = 2,
                            Name = "مصر الجديدة"
                        },
                        new
                        {
                            Id = 6,
                            GovernorateId = 2,
                            Name = "المعادي"
                        },
                        new
                        {
                            Id = 7,
                            GovernorateId = 3,
                            Name = "6 أكتوبر"
                        },
                        new
                        {
                            Id = 8,
                            GovernorateId = 3,
                            Name = "الدقي"
                        },
                        new
                        {
                            Id = 9,
                            GovernorateId = 3,
                            Name = "الهرم"
                        },
                        new
                        {
                            Id = 10,
                            GovernorateId = 4,
                            Name = "المنتزة"
                        },
                        new
                        {
                            Id = 11,
                            GovernorateId = 4,
                            Name = "سموحة"
                        },
                        new
                        {
                            Id = 12,
                            GovernorateId = 4,
                            Name = "محرم بك"
                        },
                        new
                        {
                            Id = 13,
                            GovernorateId = 5,
                            Name = "المنصورة"
                        },
                        new
                        {
                            Id = 14,
                            GovernorateId = 5,
                            Name = "طلخا"
                        },
                        new
                        {
                            Id = 15,
                            GovernorateId = 5,
                            Name = "ميت غمر"
                        },
                        new
                        {
                            Id = 16,
                            GovernorateId = 6,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 17,
                            GovernorateId = 6,
                            Name = "ملوي"
                        },
                        new
                        {
                            Id = 18,
                            GovernorateId = 6,
                            Name = "مغاغة"
                        },
                        new
                        {
                            Id = 19,
                            GovernorateId = 7,
                            Name = "سوهاج"
                        },
                        new
                        {
                            Id = 20,
                            GovernorateId = 7,
                            Name = "طهطا"
                        },
                        new
                        {
                            Id = 21,
                            GovernorateId = 7,
                            Name = "جرجا"
                        },
                        new
                        {
                            Id = 22,
                            GovernorateId = 8,
                            Name = "قنا"
                        },
                        new
                        {
                            Id = 23,
                            GovernorateId = 8,
                            Name = "نجع حمادي"
                        },
                        new
                        {
                            Id = 24,
                            GovernorateId = 8,
                            Name = "قوص"
                        },
                        new
                        {
                            Id = 25,
                            GovernorateId = 9,
                            Name = "الأقصر"
                        },
                        new
                        {
                            Id = 26,
                            GovernorateId = 9,
                            Name = "إسنا"
                        },
                        new
                        {
                            Id = 27,
                            GovernorateId = 9,
                            Name = "أرمنت"
                        },
                        new
                        {
                            Id = 28,
                            GovernorateId = 10,
                            Name = "أسوان"
                        },
                        new
                        {
                            Id = 29,
                            GovernorateId = 10,
                            Name = "كوم أمبو"
                        },
                        new
                        {
                            Id = 30,
                            GovernorateId = 10,
                            Name = "إدفو"
                        });
                });

            modelBuilder.Entity("Shyrian_project.Models.DonationOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodRequestId")
                        .HasColumnType("int");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodRequestId");

                    b.HasIndex("DonorId");

                    b.ToTable("DonationOffers");
                });

            modelBuilder.Entity("Shyrian_project.Models.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "أسيوط"
                        },
                        new
                        {
                            Id = 2,
                            Name = "القاهرة"
                        },
                        new
                        {
                            Id = 3,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الإسكندرية"
                        },
                        new
                        {
                            Id = 5,
                            Name = "المنصورة"
                        },
                        new
                        {
                            Id = 6,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 7,
                            Name = "سوهاج"
                        },
                        new
                        {
                            Id = 8,
                            Name = "قنا"
                        },
                        new
                        {
                            Id = 9,
                            Name = "الأقصر"
                        },
                        new
                        {
                            Id = 10,
                            Name = "أسوان"
                        });
                });

            modelBuilder.Entity("Shyrian_project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("CityId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shyrian_project.Models.BloodRequest", b =>
                {
                    b.HasOne("Shyrian_project.Models.BloodType", "BloodType")
                        .WithMany("BloodRequests")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shyrian_project.Models.City", null)
                        .WithMany("BloodRequests")
                        .HasForeignKey("CityId");

                    b.HasOne("Shyrian_project.Models.City", "HospitalCity")
                        .WithMany()
                        .HasForeignKey("HospitalCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shyrian_project.Models.Governorate", "HospitalGovernorate")
                        .WithMany()
                        .HasForeignKey("HospitalGovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shyrian_project.Models.User", "Requester")
                        .WithMany("MyRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shyrian_project.Models.User", "SelectedDonor")
                        .WithMany()
                        .HasForeignKey("SelectedDonorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BloodType");

                    b.Navigation("HospitalCity");

                    b.Navigation("HospitalGovernorate");

                    b.Navigation("Requester");

                    b.Navigation("SelectedDonor");
                });

            modelBuilder.Entity("Shyrian_project.Models.City", b =>
                {
                    b.HasOne("Shyrian_project.Models.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Shyrian_project.Models.DonationOffer", b =>
                {
                    b.HasOne("Shyrian_project.Models.BloodRequest", "BloodRequest")
                        .WithMany("DonationOffers")
                        .HasForeignKey("BloodRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shyrian_project.Models.User", "Donor")
                        .WithMany("DonationOffers")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Shyrian_project.Models.User", b =>
                {
                    b.HasOne("Shyrian_project.Models.BloodType", "BloodType")
                        .WithMany("Users")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shyrian_project.Models.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shyrian_project.Models.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("City");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Shyrian_project.Models.BloodRequest", b =>
                {
                    b.Navigation("DonationOffers");
                });

            modelBuilder.Entity("Shyrian_project.Models.BloodType", b =>
                {
                    b.Navigation("BloodRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Shyrian_project.Models.City", b =>
                {
                    b.Navigation("BloodRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Shyrian_project.Models.Governorate", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Shyrian_project.Models.User", b =>
                {
                    b.Navigation("DonationOffers");

                    b.Navigation("MyRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
